apiVersion: v1
kind: Secret
metadata:
  name: database-url
  namespace: staging
type: Opaque
stringData:
  DATABASE_URL: 'mysql://staging:sacr910288@127.0.0.1/staging'
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
  namespace: staging
type: Opaque
stringData:
  MYSQL_USER: 'staging'
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
  namespace: staging
type: Opaque
stringData:
  MYSQL_PASSWORD: 'sacr910288'
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db
  namespace: staging
type: Opaque
stringData:
  MYSQL_DB: 'staging'
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-dbhost
  namespace: staging
type: Opaque
stringData:
  MYSQL_DBHOST: '127.0.0.1'
---
apiVersion: v1
kind: Secret
metadata:
  name: be-url
  namespace: staging
type: Opaque
stringData:
  be-url: 'http://staging-cbr-backend:5000/api/refresh'

