apiVersion: v1
kind: Secret
metadata:
  name: database-url
  namespace: production
type: Opaque
stringData:
  DATABASE_URL: 'mysql://production:<production-db-password>@127.0.0.1/production'
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
  namespace: production
type: Opaque
stringData:
  MYSQL_USER: 'production'
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
  namespace: production
type: Opaque
stringData:
  MYSQL_PASSWORD: '<production-db-password>'
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db
  namespace: production
type: Opaque
stringData:
  MYSQL_DB: 'production'
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-dbhost
  namespace: production
type: Opaque
stringData:
  MYSQL_DBHOST: '127.0.0.1'
---
apiVersion: v1
kind: Secret
metadata:
  name: be-url
  namespace: production
type: Opaque
stringData:
  be-url: 'http://production-cbr-backend:5000/api/refresh'

